# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runeward < Formula
  desc "Governed execution cells for AI agents"
  homepage "https://github.com/Runewardd/runeward"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Runewardd/runeward/releases/download/v0.3.0/runeward_darwin_amd64.tar.gz"
      sha256 "3d4c1482dca3deb7506c43871be7eff32ab26787b5c2ed19a7b77105106fab84"

      define_method(:install) do
        bin.install "runeward"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Runewardd/runeward/releases/download/v0.3.0/runeward_darwin_arm64.tar.gz"
      sha256 "9c62177f50b073dfee137e6a4846420a64e2697217745f78f2d39adf031b5007"

      define_method(:install) do
        bin.install "runeward"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Runewardd/runeward/releases/download/v0.3.0/runeward_linux_amd64.tar.gz"
      sha256 "34a626619613937fe8971d9159203be1b1ee575e7923979bcd8673b07531287f"
      define_method(:install) do
        bin.install "runeward"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Runewardd/runeward/releases/download/v0.3.0/runeward_linux_arm64.tar.gz"
      sha256 "786ff18728a7db77129df84b04ae68c63cd846ac5fee810eaa6a8b0c77ebca39"
      define_method(:install) do
        bin.install "runeward"
      end
    end
  end

  test do
    system "#{bin}/runeward", "version"
  end
end
