# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runeward < Formula
  desc "Governed execution cells for AI agents"
  homepage "https://github.com/adefemi171/runeward"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adefemi171/runeward/releases/download/v0.1.2/runeward_darwin_amd64.tar.gz"
      sha256 "17501032bb911e111a03628f9d4545cfcbf9b5fc9b5d3999c52b49fa3ddbf160"

      define_method(:install) do
        bin.install "runeward"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adefemi171/runeward/releases/download/v0.1.2/runeward_darwin_arm64.tar.gz"
      sha256 "137c0adaf70ad9e7e14c99120e7279345495ff62fee293bc97f006acbd523436"

      define_method(:install) do
        bin.install "runeward"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/adefemi171/runeward/releases/download/v0.1.2/runeward_linux_amd64.tar.gz"
      sha256 "4076066c7e3ec60b33e52752db74028cb58f5ef8730e9efe0ff3c5816229f9f2"
      define_method(:install) do
        bin.install "runeward"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adefemi171/runeward/releases/download/v0.1.2/runeward_linux_arm64.tar.gz"
      sha256 "75da999e95d8793d5b3849bd8a06884ad02dec7fa50c355a307b5cf57c01cc10"
      define_method(:install) do
        bin.install "runeward"
      end
    end
  end

  test do
    system "#{bin}/runeward", "version"
  end
end
